package edu.wichita.iot.smart_home.comfortvote.data;

import android.widget.TextView;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Mostafa on 4/1/2016.
 */
public class ComfData {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField
    public String currentTime;

    @DatabaseField
    public String heartRateQuality;

    @DatabaseField
    public int heartRate;

    @DatabaseField
    public float accelerometerX;

    @DatabaseField
    public float accelerometerY;

    @DatabaseField
    public float accelerometerZ;

    @DatabaseField
    public float accelerometerX2;

    @DatabaseField
    public float accelerometerY2;

    @DatabaseField
    public float accelerometerZ2;

    @DatabaseField
    public float angAccelerometerX;

    @DatabaseField
    public float angAccelerometerY;

    @DatabaseField
    public float angAccelerometerZ;

    @DatabaseField
    public int brightnessVal;

    @DatabaseField
    public double airPressure;

    @DatabaseField
    public double temperature;

    @DatabaseField
    public int resistance;

    @DatabaseField
    public long caloriesToday;

    @DatabaseField
    public long caloriesTS;

    @DatabaseField
    public long caloriesToday2;

    @DatabaseField
    public long caloriesTS2;

    @DatabaseField
    public long caloriesToday3;

    @DatabaseField
    public long caloriesTS3;


    @DatabaseField
    public float skinTemperature;

    @DatabaseField
    public long uVExposureToday;

    @DatabaseField
    public String uVIndexLevel;

    @DatabaseField
    public String motionType;

    @DatabaseField
    public long distance;

    @DatabaseField
    public float pace;

    @DatabaseField
    public float speed;

    @DatabaseField
    public long totalLoss;

    @DatabaseField
    public long totalGain;

    @DatabaseField
    public long steppingGain;

    @DatabaseField
    public long steppingLoss;

    @DatabaseField
    public long steppingAscended;

    @DatabaseField
    public long steppingDescended;

    @DatabaseField
    public float rate;

    @DatabaseField
    public long flightsStairsAscended;

    @DatabaseField
    public long flightsStairsDescended;

    @DatabaseField
    public String bandContactState;

    @DatabaseField
    public long pedometer;

    @DatabaseField
    public long pedometerTS;

    @DatabaseField
    public long pedometer2;

    @DatabaseField
    public long pedometerTS2;

    @DatabaseField
    public long pedometer3;

    @DatabaseField
    public long pedometerTS3;

    @DatabaseField
    public double rrInterval;

    @DatabaseField
    public String statusStr;

    @DatabaseField
    public int vote;

    @DatabaseField
    public float roomTempreture;

    @DatabaseField
    public float roomHumidity;

    @DatabaseField
    public int locationType;

    @DatabaseField
    public float clothingScore;

    @DatabaseField
    public String clothing;


    public String getCsvFormatHeader(){
        return  "currentTime, "+
                "heartRateQuality, " +
                "heartRate, " +
                "accelerometerX, " +
                "accelerometerY, " +
                "accelerometerZ, " +
                "accelerometerX2, " +
                "accelerometerY2, " +
                "accelerometerZ2, " +
                "angAccelerometerX, " +
                "angAccelerometerY, " +
                "angAccelerometerZ, " +
                "brightnessVal, " +
                "airPressure, " +
                "temperature, " +
                "resistance, " +
                "caloriesToday, " +
                "caloriesTS, " +
                "caloriesToday2, " +
                "caloriesTS2, " +
                "caloriesToday3, " +
                "caloriesTS3, " +
                "skinTemperature, " +
                "uVExposureToday, " +
                "uVIndexLevel, " +
                "motionType, " +
                "distance, " +
                "pace, " +
                "speed, " +
                "totalLoss, " +
                "totalGain, " +
                "steppingGain, " +
                "steppingLoss, " +
                "steppingAscended, " +
                "steppingDescended, " +
                "rate, " +
                "flightsStairsAscended, " +
                "flightsStairsDescended, " +
                "bandContactState, " +
                "pedometer, " +
                "pedometerTS, " +
                "pedometer, " +
                "pedometerTS2, " +
                "pedometer2, " +
                "pedometerTS3, " +
                "rrInterval3, " +
                "statusStr, " +
                "vote, " +
                "roomTempreture, " +
                "roomHumidity, " +
                "locationType, " +
                "clothingScore, " +
                "clothing \n";
    }

    public String getCsvFormat(){
        return          String.valueOf(currentTime) + "," +
                        String.valueOf(heartRateQuality) + "," +
                        String.valueOf(heartRate) + "," +
                        String.valueOf(accelerometerX) + "," +
                        String.valueOf(accelerometerY) + "," +
                        String.valueOf(accelerometerZ) + "," +
                        String.valueOf(accelerometerX2) + "," +
                        String.valueOf(accelerometerY2) + "," +
                        String.valueOf(accelerometerZ2) + "," +
                        String.valueOf(angAccelerometerX) + "," +
                        String.valueOf(angAccelerometerY) + "," +
                        String.valueOf(angAccelerometerZ) + "," +
                        String.valueOf(brightnessVal) + "," +
                        String.valueOf(airPressure) + "," +
                        String.valueOf(temperature) + "," +
                        String.valueOf(resistance) + "," +
                        String.valueOf(caloriesToday) + "," +
                        String.valueOf(caloriesTS) + "," +
                        String.valueOf(caloriesToday2) + "," +
                        String.valueOf(caloriesTS2) + "," +
                        String.valueOf(caloriesToday3) + "," +
                        String.valueOf(caloriesTS3) + "," +
                        String.valueOf(skinTemperature) + "," +
                        String.valueOf(uVExposureToday) + "," +
                        String.valueOf(uVIndexLevel) + "," +
                        String.valueOf(motionType) + "," +
                        String.valueOf(distance) + "," +
                        String.valueOf(pace) + "," +
                        String.valueOf(speed) + "," +
                        String.valueOf(totalLoss) + "," +
                        String.valueOf(totalGain) + "," +
                        String.valueOf(steppingGain) + "," +
                        String.valueOf(steppingLoss) + "," +
                        String.valueOf(steppingAscended) + "," +
                        String.valueOf(steppingDescended) + "," +
                        String.valueOf(rate) + "," +
                        String.valueOf(flightsStairsAscended) + "," +
                        String.valueOf(flightsStairsDescended) + "," +
                        String.valueOf(bandContactState) + "," +
                        String.valueOf(pedometer) + "," +
                        String.valueOf(pedometerTS) + "," +
                        String.valueOf(pedometer2) + "," +
                        String.valueOf(pedometerTS2) + "," +
                        String.valueOf(pedometer3) + "," +
                        String.valueOf(pedometerTS3) + "," +
                        String.valueOf(rrInterval) + "," +
                        String.valueOf(statusStr) + "," +
                        String.valueOf(vote) + "," +
                        String.valueOf(roomTempreture) + "," +
                        String.valueOf(roomHumidity) +
                        String.valueOf(locationType) +
                        String.valueOf(clothingScore) +
                        String.valueOf(clothing) +  "\n" ;
    }
}
