package edu.wichita.iot.smart_home.comfortvote.data;

import android.text.format.DateFormat;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Mostafa on 4/1/2016.
 *
 */
public class SensorData {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField
    public String currentTime;

    @DatabaseField
    public String heartRateQuality;

    @DatabaseField
    public int heartRate;

    @DatabaseField
    public float accelerometerX;

    @DatabaseField
    public float accelerometerY;

    @DatabaseField
    public float accelerometerZ;

    @DatabaseField
    public float accelerometerX2;

    @DatabaseField
    public float accelerometerY2;

    @DatabaseField
    public float accelerometerZ2;

    @DatabaseField
    public float angAccelerometerX;

    @DatabaseField
    public float angAccelerometerY;

    @DatabaseField
    public float angAccelerometerZ;

    @DatabaseField
    public int brightnessVal;

    @DatabaseField
    public double airPressure;

    @DatabaseField
    public double temperature;

    @DatabaseField
    public int resistance;

    @DatabaseField
    public long caloriesToday;

    @DatabaseField
    public long caloriesTS;


    @DatabaseField
    public float skinTemperature;

    @DatabaseField
    public long uVExposureToday;

    @DatabaseField
    public String uVIndexLevel;

    @DatabaseField
    public String motionType;

    @DatabaseField
    public long distance;

    @DatabaseField
    public float pace;

    @DatabaseField
    public float speed;

    @DatabaseField
    public long totalLoss;

    @DatabaseField
    public long totalGain;

    @DatabaseField
    public long steppingGain;

    @DatabaseField
    public long steppingLoss;

    @DatabaseField
    public long steppingAscended;

    @DatabaseField
    public long steppingDescended;

    @DatabaseField
    public float rate;

    @DatabaseField
    public long flightsStairsAscended;

    @DatabaseField
    public long flightsStairsDescended;

    @DatabaseField
    public String bandContactState;

    @DatabaseField
    public long pedometer;

    @DatabaseField
    public long pedometerTS;

    @DatabaseField
    public double rrInterval;

    @DatabaseField
    public String statusStr;


    public String getCsvFormatHeader(){
        return  "currentTime, "+
                "heartRateQuality, " +
                "heartRate, " +
                "accelerometerX, " +
                "accelerometerY, " +
                "accelerometerZ, " +
                "accelerometerX2, " +
                "accelerometerY2, " +
                "accelerometerZ2, " +
                "angAccelerometerX, " +
                "angAccelerometerY, " +
                "angAccelerometerZ, " +
                "brightnessVal, " +
                "airPressure, " +
                "temperature, " +
                "resistance, " +
                "caloriesToday, " +
                "caloriesTS, " +
                "skinTemperature, " +
                "uVExposureToday, " +
                "uVIndexLevel, " +
                "motionType, " +
                "distance, " +
                "pace, " +
                "speed, " +
                "totalLoss, " +
                "totalGain, " +
                "steppingGain, " +
                "steppingLoss, " +
                "steppingAscended, " +
                "steppingDescended, " +
                "rate, " +
                "flightsStairsAscended, " +
                "flightsStairsDescended, " +
                "bandContactState, " +
                "pedometer, " +
                "pedometerTS, " +
                "rrInterval, " +
                "statusStr \n";
    }

    public String getCsvFormat(){
        return          String.valueOf(currentTime) + "," +
                        String.valueOf(heartRateQuality) + "," +
                        String.valueOf(heartRate) + "," +
                        String.valueOf(accelerometerX) + "," +
                        String.valueOf(accelerometerY) + "," +
                        String.valueOf(accelerometerZ) + "," +
                        String.valueOf(accelerometerX2) + "," +
                        String.valueOf(accelerometerY2) + "," +
                        String.valueOf(accelerometerZ2) + "," +
                        String.valueOf(angAccelerometerX) + "," +
                        String.valueOf(angAccelerometerY) + "," +
                        String.valueOf(angAccelerometerZ) + "," +
                        String.valueOf(brightnessVal) + "," +
                        String.valueOf(airPressure) + "," +
                        String.valueOf(temperature) + "," +
                        String.valueOf(resistance) + "," +
                        String.valueOf(caloriesToday) + "," +
                        String.valueOf(caloriesTS) + "," +
                        String.valueOf(skinTemperature) + "," +
                        String.valueOf(uVExposureToday) + "," +
                        String.valueOf(uVIndexLevel) + "," +
                        String.valueOf(motionType) + "," +
                        String.valueOf(distance) + "," +
                        String.valueOf(pace) + "," +
                        String.valueOf(speed) + "," +
                        String.valueOf(totalLoss) + "," +
                        String.valueOf(totalGain) + "," +
                        String.valueOf(steppingGain) + "," +
                        String.valueOf(steppingLoss) + "," +
                        String.valueOf(steppingAscended) + "," +
                        String.valueOf(steppingDescended) + "," +
                        String.valueOf(rate) + "," +
                        String.valueOf(flightsStairsAscended) + "," +
                        String.valueOf(flightsStairsDescended) + "," +
                        String.valueOf(bandContactState) + "," +
                        String.valueOf(pedometer) + "," +
                        String.valueOf(pedometerTS) + "," +
                        String.valueOf(rrInterval) + "," +
                        String.valueOf(statusStr) +  "\n" ;
    }


    public static SensorData newInstance(final ComfData comfData){
        SensorData sensorData = new SensorData();

        sensorData.currentTime = DateFormat.format("MM/dd/yyyy HH:mm:ss", System.currentTimeMillis()).toString();
        sensorData.heartRateQuality = comfData.heartRateQuality;
        sensorData.heartRate = comfData.heartRate;
        sensorData.accelerometerX = comfData.accelerometerX;
        sensorData.accelerometerY = comfData.accelerometerY;
        sensorData.accelerometerZ = comfData.accelerometerZ;
        sensorData.accelerometerX2 = comfData.accelerometerX2;
        sensorData.accelerometerY2 = comfData.accelerometerY2;
        sensorData.accelerometerZ2 = comfData.accelerometerZ2;
        sensorData.angAccelerometerX = comfData.angAccelerometerX;
        sensorData.angAccelerometerY = comfData.angAccelerometerY;
        sensorData.angAccelerometerZ = comfData.angAccelerometerZ;
        sensorData.brightnessVal = comfData.brightnessVal;
        sensorData.airPressure = comfData.airPressure;
        sensorData.temperature = comfData.temperature;
        sensorData.resistance = comfData.resistance;
        sensorData.caloriesToday = comfData.caloriesToday;
        sensorData.caloriesTS = comfData.caloriesTS;
        sensorData.skinTemperature = comfData.skinTemperature;
        sensorData.uVExposureToday = comfData.uVExposureToday;
        sensorData.uVIndexLevel = comfData.uVIndexLevel;
        sensorData.motionType = comfData.motionType;
        sensorData.distance = comfData.distance;
        sensorData.pace = comfData.pace;
        sensorData.speed = comfData.speed;
        sensorData.totalLoss = comfData.totalLoss;
        sensorData.totalGain = comfData.totalGain;
        sensorData.steppingGain = comfData.steppingGain;
        sensorData.steppingLoss = comfData.steppingLoss;
        sensorData.steppingAscended = comfData.steppingAscended;
        sensorData.steppingDescended = comfData.steppingDescended;
        sensorData.rate = comfData.rate;
        sensorData.flightsStairsAscended = comfData.flightsStairsAscended;
        sensorData.flightsStairsDescended = comfData.flightsStairsDescended;
        sensorData.bandContactState = comfData.bandContactState;
        sensorData.pedometer = comfData.pedometer;
        sensorData.pedometerTS = comfData.pedometerTS;
        sensorData.rrInterval = comfData.rrInterval;
        sensorData.statusStr = comfData.statusStr;

        return sensorData;
    }

}
