package edu.wichita.iot.smart_home.comfortvote.data;

import com.j256.ormlite.field.DatabaseField;

/**
 * Created by Fariba on 4/22/2016.
 */
public class SettingData {
    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    public int id;

    @DatabaseField
    public int samplingInterval;

    @DatabaseField
    public int samplingWaitTime;

    @DatabaseField
    public int notificationInterval;

}
